# .github/workflows/deploy.yml
name: Deploy Website

on:
  push:
    branches:
      - main  # 你要部署的分支，建議是 main

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Build project
        run: |
          npm install
          npm run build || echo "沒有 build 指令，跳過"

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./  # 部署整個專案根目錄 (index.html 要在這裡)

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
